services:
  - type: web
    name: sc-river
    runtime: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
    plan: free
